### ISSUE TITLE
variable font

### ISSUE THREAD

**Issue by subframe7536** [subframe7536/maple-font#27]
https://github.com/users/subframe7536/projects/1

**Comment by subframe7536** [comment]
early stage
![show](https://github.com/subframe7536/maple-font/assets/78338239/39d25f40-5fca-4511-a69e-e7b8f0596b27)

**Comment by subframe7536** [comment]
Maybe result in a modified version of `Jetbrains Mono`

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/maple-font/assets/78338239/1466af0d-191a-405c-83dc-a51fe12b1228)
none-ligature characters schedule

**Comment by subframe7536** [comment]
the `.glyphs` file generated by FontLab maybe cannot directly compile to font using fontmake

considering use ttx files as source file like V6

**Comment by subframe7536** [comment]
![image](https://github.com/subframe7536/maple-font/assets/78338239/e6b547ac-cfb2-4317-a261-28336cfd3288)

symbols and ligatures

**Comment by subframe7536** [comment]
update

![recording](https://github.com/subframe7536/maple-font/assets/78338239/5d955d65-503c-44ee-99a4-91d8a7abf0cc)

**Comment by subframe7536** [comment]
There is too few open tutorials/guide about fonttools/fontlab scripts/fontmake...

**Comment by chmielcode** [comment]
This is some great font and thanks to it's thickness it renders perfectly in most cases. However, I find the V7 shape of "a" standing out too much and it distracts me. I know, maybe it's just me, but it would be nice to have a more straight variant (possibly as default). Thank you very much for your work :)

**Comment by subframe7536** [comment]
@chmielcode Thanks for your feedback! There still a lot of works to migrate all the cursive characters, variants and stylesets from v6. 

Maybe you need the variant of `cv03` in v6? It offers a more generic style of "a"

**Comment by chmielcode** [comment]
Yes, CV03 variant looks great and would make for a great default version of "a" in my opinion. Then again I believe I can "freeze" the font with cv03 enabled as soon as it's available so that all tools I use display it correctly. Or maybe I'll just get used to it :) There is no going back from V7 for me since it has polish letters.

**Comment by subframe7536** [comment]
alternative `a` is changed to `cv02` in V7

**Comment by zetaloop** [comment]
> Can anyone tell me what are the usage scenarios for the ligatures of `--}}` `{{--` `{!--` `{!!` `!!}` `<#--`？

Looks like some comment or variable blocks in HTML template engines such as Blade, Handlebars and FreeMarker.

```blade
{{-- Blade comment --}}
{!! $Blade_raw_html !!}
```
```handlebars
{{!-- Handlebars comment --}}
```
```freemarker
<#-- FreeMarker comment -->
```

However Handlebars uses `{{!--` rather than `{!--`. I didn't find much information about `{!--` on GitHub.

**Comment by subframe7536** [comment]
@zetaloop Thanks for your explaination. I will restore them in next release

**Comment by subframe7536** [comment]
[src-font.zip](https://github.com/subframe7536/maple-font/files/14323353/src-font.zip)
test italic

**Comment by subframe7536** [comment]
it seems that italic style cannot properly recognized on Windows

**Comment by subframe7536** [comment]
update

![Image](https://github.com/subframe7536/maple-font/assets/78338239/393cc661-ee31-4c1d-bdbd-d56d1c4d4c96)

**Comment by chmielcode** [comment]
@subframe7536 To make Maple Mono VF work on Windows with italics I had to rename Font family from "Maple Mono Italic" to "Maple Mono" using Font Forge.
![obraz](https://github.com/subframe7536/maple-font/assets/45938987/9fb66666-0d22-485c-b211-516908a38de3)
I'm no font expert, but I hope it helps :)

**Comment by subframe7536** [comment]
Almost all the work have been done.

**Comment by subframe7536** [comment]
@chmielcode Thanks for your advice. This issue should be fixed in v7-beta4, you can have a try

**Comment by chmielcode** [comment]
@subframe7536 Yes, variable font looks and should work fine now with b4. Thank you! Static fonts (ttf autohinted) still have separate family names per variant though. Some apps know how to deal with it and some (notably Notepad++) don't.

**Comment by subframe7536** [comment]
@chmielcode I think the family name in current version have already been handled, can you provide more info or examples?

Maple Mono's config:
![image](https://github.com/subframe7536/maple-font/assets/78338239/16fbb069-2265-4d33-ae0c-e357cbe1520e)

Other variable fonts' config:

![image](https://github.com/subframe7536/maple-font/assets/78338239/28258366-7129-464c-88a5-a869a80a7749)

![image](https://github.com/subframe7536/maple-font/assets/78338239/e38b31d5-d194-4647-943d-0d05d633d682)

![image](https://github.com/subframe7536/maple-font/assets/78338239/d142fa89-3630-494f-a7fd-0a8510f48656)

**Comment by chmielcode** [comment]
Out of the box font selection for b4 ttfautohint static release:
![obraz](https://github.com/subframe7536/maple-font/assets/45938987/f3781535-2556-4dde-ad75-30e8a896d20f)
In this case some (most?) windows apps cannot link Regular to Bold and other variants.

Fixed by removing variant (e.g. Regular, Bold etc.) name from Font family:
![obraz](https://github.com/subframe7536/maple-font/assets/45938987/45938824-7cdd-43e3-92b3-fb6ba235b66e)

@subframe7536  Here is my edited version of b3 for you too look at. Maybe the difference will be easier to spot this way. *Linegap change is irrelevant.
[mm7bs_fix_lg30.zip](https://github.com/subframe7536/maple-font/files/14395571/mm7bs_fix_lg30.zip)

**Comment by subframe7536** [comment]
seems that it is caused by "style group" and make them same will cause #141

**Comment by chmielcode** [comment]
@subframe7536 Hmmm... Screenshots you took of JetBrains Mono Style Groups tell me that this is not the same thing.
![obraz](https://github.com/subframe7536/maple-font/assets/45938987/4357260b-a0ae-48ea-9f48-8abad4c8a3aa)

Beta4
![obraz](https://github.com/subframe7536/maple-font/assets/45938987/3789a81f-4d14-4c23-8278-7d78543e7f3d)

Beta5
![obraz](https://github.com/subframe7536/maple-font/assets/45938987/9a64125f-a0d5-4c08-a57a-5e2da0245670)

So now beta5 should work fine as JetBrains Mono does on Windows. I believe it could be conventional since, as mentioned before, some apps can work around it and find other styles without common Font family name. I don't know. If this change breaks everything else I'm perfectly fine with making the font family change for myself :) Already using (fixed) b3 everywhere with no issues at all.

**Comment by subframe7536** [comment]
I think Roboto Mono's principle is maybe better

![image](https://github.com/subframe7536/maple-font/assets/78338239/fcded996-ae93-4231-bfcd-b50446d511aa)
- Roboto Mono: regular, bold, italic, bold italic
- Roboto Light: light, light italic
- Roboto Medium: medium, medium light
- Roboto Think: thin, thin italic
